# conda env create --file environment.yml
name: customer_churn
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.11
  - pip:
    - pyhere
    - virtualenv
    # create virtual environment using virtualenv
post-link: |
    virtualenv env
    source env/Scripts/activate
    pip install -r requirements.txt